# Generated by Django 4.1.5 on 2023-02-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Clothes', 'Clothes'), ('Sport', 'Sport'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Toys', 'Toys')], max_length=20)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
