# Generated by Django 4.1.5 on 2023-02-09 14:48

from django.db import migrations, models
import random

def populate(apps, schema_editor):
    Product = apps.get_model('product', 'Product')

    for i in range(10000):
        title = "Product" + str(i)
        price = random.randint(50, 2000)
        list = ['Clothes', 'Sport', 'Electronics', 'Home', 'Toys']
        category = random.choice(list)
        description = "description" + str(i)
        obj = Product(title=title, price=price, category=category, description=description)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Sport', 'Sport'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Toys', 'Toys')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(db_index=True),
        ),
        migrations.RunPython(populate),
    ]
